### ISSUE TITLE
[OUR MEMBERS] reduce size of icons

### ISSUE THREAD

**Issue by allypalanzi** [dcfemtech/dcfemtech.github.io#16]
- need to reduce size of icons
- maybe make these text only? all of the icons are so different it looks jarring 😱
- or maybe make the much smaller and display the name in text too

**Comment by sirjessthebrave** [comment]
yah i know - maybe when they are smaller they wont be SO different? I am not 100% sure the best way to deal with this - maybe text on front page and members list is single column?

**Comment by sirjessthebrave** [comment]
What about a carousel of members on the front page?
