### ISSUE TITLE
Add padding or margin to response text for mailing list sign up

### ISSUE THREAD

**Issue by jackiekazil** [dcfemtech/dcfemtech.github.io#24]
On this page:  http://dcfemtech.github.io/dcft-website/involve.html
A little bit of space needs to be added between the response text that appears after you hit the sign up button. See screenshot below... 

<img width="996" alt="screen shot 2016-09-06 at 10 57 06 pm" src="https://cloud.githubusercontent.com/assets/166734/18298433/ac2e119a-7486-11e6-98e5-91bde6aabd71.png">

**Comment by allypalanzi** [comment]
Fixed! Thanks!
