### ISSUE TITLE
bring over historical DCFT award winners

### ISSUE THREAD

**Issue by sirjessthebrave** [dcfemtech/dcfemtech.github.io#37]
add names for the 2015 and 2016 DCFT award winners - perhaps a few photos

**Comment by allypalanzi** [comment]
we have this: https://dcfemtech.github.io/awards-2015.html https://dcfemtech.github.io/awards-2016.html linked on the Awards page

**Comment by sirjessthebrave** [comment]
ahh ok!  should we have the 'event' link go to that page then instead of the small 'event' page?

**Comment by sirjessthebrave** [comment]
so instead of this page: https://dcfemtech.github.io/awards-event-2017
