### ISSUE TITLE
Setup so all pages are "dcfemtech.com" and not a redirect, use cloudflare for https

### ISSUE THREAD

**Issue by allypalanzi** [dcfemtech/dcfemtech.github.io#46]
https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/

**Comment by allypalanzi** [comment]
@shannonturner do you think you could look into this since you own the dcfemtech domain? i set this up for my personal site and it was pretty simple

**Comment by shannonturner** [comment]
In progress! Created a Cloudflare account, changed over the nameservers and will update with the status here.

**Comment by allypalanzi** [comment]
omg ❤️ so fast

**Comment by shannonturner** [comment]
Aaand we're live! https://dcfemtech.com/

**Comment by allypalanzi** [comment]
im getting a 404, but maybe it'll just take a bit

**Comment by shannonturner** [comment]
Is it the Google broken robot trying to fix itself 404? I was getting that one for a few minutes too but we should be good.

I'll keep an eye on it but let me know if you still are getting the 404 in 24-48 hours!
