### ISSUE TITLE
Extra </ul> </div> on "Inspire" page?

### ISSUE THREAD

**Issue by lbeaufort** [dcfemtech/dcfemtech.github.io#53]
Hi @allypalanzi!

When I go to [this page](http://dcfemtech.com/inspire-2019) I see an extra `</ul> </div>`:
<img width="1061" alt="screen shot 2019-03-06 at 4 44 39 pm" src="https://user-images.githubusercontent.com/31420082/53916199-8590a300-402f-11e9-933d-7b38cb5f6086.png">

I think there might be a missing `</li>` in [this file](https://raw.githubusercontent.com/dcfemtech/dcfemtech.github.io/0d979cab30b164dfa116d0650cbb1680a424e09d/_events/inspire-2019.markdown) for the "Make Offices" line. Unfortunately,  I can't reproduce the issue locally so I can't tell for sure whether that will fix the issue.

If you agree with the change, I'd love to put in a PR!

Thanks!

**Comment by allypalanzi** [comment]
oh wow, nice catch! yes please go ahead and make a PR if you can!
